services:
  metaafzar_back_service:
    image: metaafzar_back:1.0
    ports:
      - "8930:8930"
    env_file:
      - .env

    volumes:
      - ./data:/app/data
      - ./DB:/app/DB
      - ./logs:/app/logs
      - ./static:/app/staticfiles
    networks:
      - web_net
    restart: always

networks:
  web_net:
    external: true

