services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    volumes:
      - ./v2ray/config.json:/etc/v2ray/config.json
    ports:
      - "1080:1080"   # SOCKS
      - "8880:8080"   # HTTP proxy (if enabled)
    restart: unless-stopped
    command: ["run", "-config=/etc/v2ray/config.json"]

  metaafzar_back_service:
    depends_on:
      - v2ray
    image: metaafzar_back:1.0
    ports:
      - "8930:8930"
    env_file:
      - .env

    environment:
      HTTP_PROXY: http://v2ray:8080
      HTTPS_PROXY: http://v2ray:8080

    volumes:
      - ./data:/app/data
      - ./DB:/app/DB
      - ./logs:/app/logs
      - ./static:/app/staticfiles
    networks:
      - web_net
    restart: always

networks:
  web_net:
    external: true

