# Generated by Django 5.2.4 on 2025-08-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_scraper', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='igpage',
            old_name='token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='igpage',
            name='ig_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='igpage',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='igpage',
            name='date_scraped',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='igpage',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='igpage',
            name='following',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='igpage',
            name='posts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
