# Generated by Django 4.2.23 on 2025-08-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_scraper', '0005_rename_token_igpage_access_token_igpage_ig_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='igpage',
            name='permissions',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='igpage',
            name='access_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='igpage',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
