"""
Django settings for metaafzar project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from env import my_env as MY_ENVS
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = MY_ENVS.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = MY_ENVS.DEBUG

if not DEBUG:
    SWAGGER_SETTINGS = {
        'DEFAULT_API_URL': 'https://metaafzar.bytecraft.ir/',
    }

LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'django.log'),
        },
    },
    'loggers': {
        '': {  # root logger
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

SECURE_COOKIES = True if MY_ENVS.ENVIRONMENT == 'production' else False
ALLOWED_HOSTS = MY_ENVS.ALLOWED_HOSTS

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'my_scraper',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = MY_ENVS.ROOT_URLCONF

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'metaafzar.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# # Uncomment and configure the following for production database settings
# if MY_ENVS.ENVIRONMENT == 'production':
#     DATABASES = {
#         'default': {
#             'ENGINE': MY_ENVS.DATABASE_ENGINE,
#             'NAME': MY_ENVS.DATABASE_NAME,
#             'USER': MY_ENVS.DATABASE_USER,
#             'PASSWORD': MY_ENVS.DATABASE_PASSWORD,
#             'HOST': MY_ENVS.DATABASE_HOST,
#             'PORT': MY_ENVS.DATABASE_PORT,
#         }
#     }

if MY_ENVS.DATABASE_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': MY_ENVS.DATABASE_ENGINE,
            'NAME': BASE_DIR / MY_ENVS.DATABASE_NAME,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': MY_ENVS.DATABASE_ENGINE,
            'NAME': MY_ENVS.DATABASE_NAME,
            'USER': MY_ENVS.DATABASE_USER,
            'PASSWORD': MY_ENVS.DATABASE_PASSWORD,
            'HOST': MY_ENVS.DATABASE_HOST,
            'PORT': MY_ENVS.DATABASE_PORT,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'my_scraper.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CSRF_TRUSTED_ORIGINS = [
    'https://metaafzar.bytecraft.ir',
]

CORS_ALLOWED_ORIGINS = [
    'https://metaafzar.bytecraft.ir',
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema'
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'MetaAfzar API Documentation',
    'DESCRIPTION': 'MetaAfzar is a tool for scraping Instagram business pages and managing user data. This API '
                   'provides endpoints for user management, Instagram page attachment, and scraping functionalities. '
                   'This API Developed by ByteCraft.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=180),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1)
}
